In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime

In [3]:
# Get the s&p500 overall data
sp500 = yf.Ticker("^GSPC")
sp500 = sp500.history(period="max")
sp500

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1927-12-30 00:00:00-05:00,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
1928-01-03 00:00:00-05:00,17.760000,17.760000,17.760000,17.760000,0,0.0,0.0
1928-01-04 00:00:00-05:00,17.719999,17.719999,17.719999,17.719999,0,0.0,0.0
1928-01-05 00:00:00-05:00,17.549999,17.549999,17.549999,17.549999,0,0.0,0.0
1928-01-06 00:00:00-05:00,17.660000,17.660000,17.660000,17.660000,0,0.0,0.0
...,...,...,...,...,...,...,...
2024-10-21 00:00:00-04:00,5857.819824,5866.919922,5824.790039,5853.979980,3407010000,0.0,0.0
2024-10-22 00:00:00-04:00,5832.700195,5863.040039,5821.169922,5851.200195,3342080000,0.0,0.0
2024-10-23 00:00:00-04:00,5834.500000,5834.850098,5762.410156,5797.419922,3532650000,0.0,0.0
2024-10-24 00:00:00-04:00,5817.799805,5817.799805,5784.919922,5809.859863,3543030000,0.0,0.0
2024-10-25 00:00:00-04:00,5826.750000,5862.819824,5799.979980,5808.120117,3501280000,0.0,0.0

In [3]:
constituents = pd.read_csv('Data/stocks/constituents.csv')
print(constituents.head())

  Symbol             Security             GICS Sector  \
0    MMM                   3M             Industrials
1    AOS          A. O. Smith             Industrials
2    ABT  Abbott Laboratories             Health Care
3   ABBV               AbbVie             Health Care
4    ACN            Accenture  Information Technology

                GICS Sub-Industry    Headquarters Location  Date added  \
0        Industrial Conglomerates    Saint Paul, Minnesota  1957-03-04
1               Building Products     Milwaukee, Wisconsin  2017-07-26
2           Health Care Equipment  North Chicago, Illinois  1957-03-04
3                   Biotechnology  North Chicago, Illinois  2012-12-31
4  IT Consulting & Other Services          Dublin, Ireland  2011-07-06

       CIK      Founded
0    66740         1902
1    91142         1916
2     1800         1888
3  1551152  2013 (1888)
4  1467373         1989

In [7]:


# Create an empty dictionary to store the data for each ticker
ticker_data = {}

# Download the historical market data for the ticker
 # Create a list of ticker symbols
ticker_strings = constituents['Symbol'].tolist()

# Download the historical market data for all tickers
ticker_data = yf.download(ticker_strings, group_by='Ticker', start='2018-01-01', end='2024-01-01')
ticker_data = ticker_data.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index(level=1)

[*********************100%***********************]  503 of 503 completed

6 Failed downloads:
['SW', 'SOLV', 'GEV', 'AMTM']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2018-01-01 -> 2024-01-01) (Yahoo error = "Data doesn\'t exist for startDate = 1514782800, endDate = 1704085200")')
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2018-01-01 -> 2024-01-01)')

In [12]:
yf.Ticker('BRK.A').history(period='1d', interval='1m')

$BRK.A: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [8]:
ticker_data

Price,Ticker,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,,
2018-01-02 00:00:00+00:00,A,65.523422,67.599998,67.889999,67.339996,67.419998,1047800.0
2018-01-02 00:00:00+00:00,AAPL,41.310070,43.064999,43.075001,42.314999,42.540001,102223600.0
2018-01-02 00:00:00+00:00,ABBV,79.061188,98.410004,98.900002,96.750000,97.139999,4561300.0
2018-01-02 00:00:00+00:00,ABT,54.864079,58.790001,59.200001,57.820000,58.200001,10112800.0
2018-01-02 00:00:00+00:00,ACGL,29.433332,29.433332,30.420000,29.383333,30.403334,1333500.0
...,...,...,...,...,...,...,...
2023-12-29 00:00:00+00:00,XYL,114.360001,114.360001,114.680000,113.930000,114.089996,698900.0
2023-12-29 00:00:00+00:00,YUM,130.660004,130.660004,131.250000,130.210007,130.410004,1196800.0
2023-12-29 00:00:00+00:00,ZBH,121.699997,121.699997,122.400002,121.239998,121.459999,849600.0
2023-12-29 00:00:00+00:00,ZBRA,273.329987,273.329987,276.309998,272.769989,274.730011,251300.0
2023-12-29 00:00:00+00:00,ZTS,197.369995,197.369995,198.009995,196.250000,196.679993,1007200.0

In [ ]:
#read ticker_data to csv
ticker_data.to_csv('ticker_data.csv')

In [7]:
# Create an empty dictionary to store the data for each ticker
ticker_data2012 = {}

# Download the historical market data for the ticker
 # Create a list of ticker symbols
ticker_strings = constituents['Symbol'].tolist()

# Download the historical market data for all tickers
ticker_data2012 = yf.download(ticker_strings, group_by='Ticker', start='2012-01-01', end='2018-01-01')
ticker_data2012 = ticker_data2012.stack(level=0).rename_axis(['Date', 'Ticker']).reset_index(level=1)

[*********************100%***********************]  503 of 503 completed

23 Failed downloads:
['FOXA', 'CARR', 'UBER', 'PLTR', 'MRNA', 'CRWD', 'DOW', 'VICI', 'ABNB', 'GEHC', 'VLTO', 'CTVA', 'FOX', 'AMTM', 'OTIS', 'DAY', 'GEV', 'SW', 'KVUE', 'CEG', 'SOLV']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2012-01-01 -> 2018-01-01) (Yahoo error = "Data doesn\'t exist for startDate = 1325394000, endDate = 1514782800")')
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2012-01-01 -> 2018-01-01)')
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

In [9]:
ticker_data2012
#read ticker_data to csv
ticker_data2012.to_csv('ticker_data2012.csv')