In [3]:
pip install yfinance --upgrade --no-cache-dir

Collecting yfinance
  Downloading yfinance-0.2.48-py2.py3-none-any.whl (101 kB)
     |████████████████████████████████| 101 kB 9.3 MB/s ta 0:00:011
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Collecting peewee>=3.16.2
  Downloading peewee-3.17.7.tar.gz (939 kB)
     |████████████████████████████████| 939 kB 26.3 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/lxml/
Collecting lxml>=4.9.1
  Downloading lxml-5.3.0-cp38-cp38-macosx_10_9_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 47.6 MB/s eta 0:00:01
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 16.4 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: requests>=2.31 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from yfinance) (2.32.3)
Collecting platformdirs>=2.0.0
  Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
Collecting pytz>=2022.5
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 32.7 MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: html5lib>=1.1 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from yfinance) (1.1)
Requirement already satisfied, skipping upgrade: numpy>=1.16.5 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from yfinance) (1.24.4)
Requirement already satisfied, skipping upgrade: pandas>=1.3.0 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from yfinance) (2.0.3)
Collecting frozendict>=2.3.4
  Downloading frozendict-2.4.6-cp38-cp38-macosx_10_9_x86_64.whl (37 kB)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.0.1)
Requirement already satisfied, skipping upgrade: urllib3<3,>=1.21.1 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance) (1.25.11)
Requirement already satisfied, skipping upgrade: charset-normalizer<4,>=2 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance) (3.4.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance) (2020.6.20)
Requirement already satisfied, skipping upgrade: idna<4,>=2.5 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from requests>=2.31->yfinance) (2.10)
Requirement already satisfied, skipping upgrade: six>=1.9 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from html5lib>=1.1->yfinance) (1.15.0)
Requirement already satisfied, skipping upgrade: webencodings in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.8.2 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied, skipping upgrade: tzdata>=2022.1 in /Users/nsusser/opt/anaconda3/lib/python3.8/site-packages (from pandas>=1.3.0->yfinance) (2024.2)
Building wheels for collected packages: peewee
  Building wheel for peewee (PEP 517) ... done
  Created wheel for peewee: filename=peewee-3.17.7-cp38-cp38-macosx_10_9_x86_64.whl size=282923 sha256=d05da6d83c6a37befd7a93638bf71e396e5f31505aa09c9b08b92f0107522898
  Stored in directory: /private/var/folders/4c/79cv38ss4p33v55cqytbn83m0000gp/T/pip-ephem-wheel-cache-qrc5ql8s/wheels/31/67/77/ed24841df39598537a2aa4f55cd7c9183ec35711fe099fde29
Successfully built peewee
Installing collected packages: multitasking, peewee, lxml, beautifulsoup4, platformdirs, pytz, frozendict, yfinance
  Attempting uninstall: lxml
    Found existing installation: lxml 4.6.1
    Uninstalling lxml-4.6.1:
      Successfully uninstalled lxml-4.6.1
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.9.3
    Uninstalling beautifulsoup4-4.9.3:
      Successfully uninstalled beautifulsoup4-4.9.3
  Attempting uninstall: pytz
    Found existing installation: pytz 2020.1
    Uninstalling pytz-2020.1:
      Successfully uninstalled pytz-2020.1
Successfully installed beautifulsoup4-4.12.3 frozendict-2.4.6 lxml-5.3.0 multitasking-0.0.11 peewee-3.17.7 platformdirs-4.3.6 pytz-2024.2 yfinance-0.2.48
Note: you may need to restart the kernel to use updated packages.

In [4]:
import yfinance as yf

/Users/nsusser/opt/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [8]:
msft = yf.Ticker('MSFT')

# return a df
hist = msft.history(period='1mo')

In [9]:
msft = yf.Ticker('TSLA')

# return a df
tsla_hist = msft.history(start='2019-12-31', end='2020-01-10')

In [10]:
tsla_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2019-12-31 00:00:00-05:00,27.000000,28.086000,26.805332,27.888666,154285500,0.0,0.0
2020-01-02 00:00:00-05:00,28.299999,28.713333,28.114000,28.684000,142981500,0.0,0.0
2020-01-03 00:00:00-05:00,29.366667,30.266666,29.128000,29.534000,266677500,0.0,0.0
2020-01-06 00:00:00-05:00,29.364668,30.104000,29.333332,30.102667,151995000,0.0,0.0
2020-01-07 00:00:00-05:00,30.760000,31.441999,30.224001,31.270666,268231500,0.0,0.0
2020-01-08 00:00:00-05:00,31.580000,33.232666,31.215334,32.809334,467164500,0.0,0.0
2020-01-09 00:00:00-05:00,33.139999,33.253334,31.524668,32.089333,426606000,0.0,0.0

In [11]:
hist.dtypes

Open            float64
High            float64
Low             float64
Close           float64
Volume            int64
Dividends       float64
Stock Splits    float64
dtype: object

In [12]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-09-25 00:00:00-04:00,252.539993,257.049988,252.279999,257.019989,65034300,0.0,0.0
2024-09-26 00:00:00-04:00,260.600006,261.750000,251.529999,254.220001,67142200,0.0,0.0
2024-09-27 00:00:00-04:00,257.380005,260.700012,254.119995,260.459991,70988100,0.0,0.0
2024-09-30 00:00:00-04:00,259.040009,264.859985,255.770004,261.630005,80705700,0.0,0.0
2024-10-01 00:00:00-04:00,262.670013,263.980011,248.529999,258.019989,87397600,0.0,0.0
2024-10-02 00:00:00-04:00,247.550003,251.160004,241.500000,249.020004,93983900,0.0,0.0
2024-10-03 00:00:00-04:00,244.479996,249.789993,237.809998,240.660004,80729200,0.0,0.0
2024-10-04 00:00:00-04:00,246.690002,250.960007,244.580002,250.080002,86573200,0.0,0.0
2024-10-07 00:00:00-04:00,249.000000,249.830002,240.699997,240.830002,68113300,0.0,0.0
2024-10-08 00:00:00-04:00,243.559998,246.210007,240.559998,244.500000,56303200,0.0,0.0
2024-10-09 00:00:00-04:00,243.820007,247.429993,239.509995,241.050003,66289500,0.0,0.0
2024-10-10 00:00:00-04:00,241.809998,242.789993,232.339996,238.770004,83087100,0.0,0.0
2024-10-11 00:00:00-04:00,220.130005,223.339996,214.380005,217.800003,142628900,0.0,0.0
2024-10-14 00:00:00-04:00,220.130005,221.910004,213.740005,219.160004,86291900,0.0,0.0
2024-10-15 00:00:00-04:00,220.009995,224.259995,217.119995,219.570007,62988800,0.0,0.0
2024-10-16 00:00:00-04:00,221.399994,222.820007,218.929993,221.330002,49632800,0.0,0.0
2024-10-17 00:00:00-04:00,221.589996,222.080002,217.899994,220.889999,50791800,0.0,0.0
2024-10-18 00:00:00-04:00,220.710007,222.279999,219.229996,220.699997,49611900,0.0,0.0
2024-10-21 00:00:00-04:00,218.899994,220.479996,215.729996,218.850006,47329000,0.0,0.0
2024-10-22 00:00:00-04:00,217.309998,218.220001,215.259995,217.970001,43268700,0.0,0.0
2024-10-23 00:00:00-04:00,217.130005,218.720001,212.110001,213.649994,80938900,0.0,0.0
2024-10-24 00:00:00-04:00,244.679993,262.119995,242.649994,260.480011,204491900,0.0,0.0
2024-10-25 00:00:00-04:00,255.990005,269.440002,255.320007,266.970093,141578617,0.0,0.0

In [14]:
msft.history_metadata

{'currency': 'USD',
 'symbol': 'TSLA',
 'exchangeName': 'NMS',
 'fullExchangeName': 'NasdaqGS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 1277818200,
 'regularMarketTime': 1729884060,
 'hasPrePostMarketData': True,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 266.84,
 'fiftyTwoWeekHigh': 269.44,
 'fiftyTwoWeekLow': 255.32,
 'regularMarketDayHigh': 269.44,
 'regularMarketDayLow': 255.32,
 'regularMarketVolume': 141467020,
 'longName': 'Tesla, Inc.',
 'shortName': 'Tesla, Inc.',
 'chartPreviousClose': 27.647,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'start': 1729843200,
   'end': 1729863000,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'start': 1729863000,
   'end': 1729886400,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'start': 1729886400,
   'end': 1729900800,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [15]:
msft.info

{'address1': '1 Tesla Road',
 'city': 'Austin',
 'state': 'TX',
 'zip': '78725',
 'country': 'United States',
 'phone': '512 516 8177',
 'website': 'https://www.tesla.com',
 'industry': 'Auto Manufacturers',
 'industryKey': 'auto-manufacturers',
 'industryDisp': 'Auto Manufacturers',
 'sector': 'Consumer Cyclical',
 'sectorKey': 'consumer-cyclical',
 'sectorDisp': 'Consumer Cyclical',
 'longBusinessSummary': 'Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally. The company operates in two segments, Automotive, and Energy Generation and Storage. The Automotive segment offers electric vehicles, as well as sells automotive regulatory credits; and non-warranty after-sales vehicle, used vehicles, body shop and parts, supercharging, retail merchandise, and vehicle insurance services. This segment also provides sedans and sport utility vehicles through direct and used vehicle sales, a network of Tesla Superchargers, and in-app upgrades; purchase financing and leasing services; services for electric vehicles through its company-owned service locations and Tesla mobile service technicians; and vehicle limited warranties and extended service plans. The Energy Generation and Storage segment engages in the design, manufacture, installation, sale, and leasing of solar energy generation and energy storage products, and related services to residential, commercial, and industrial customers and utilities through its website, stores, and galleries, as well as through a network of channel partners; and provision of service and repairs to its energy product customers, including under warranty, as well as various financing options to its solar customers. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was incorporated in 2003 and is headquartered in Austin, Texas.',
 'fullTimeEmployees': 140473,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Elon R. Musk',
   'age': 51,
   'title': 'Co-Founder, Technoking of Tesla, CEO & Director',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Vaibhav  Taneja',
   'age': 45,
   'title': 'Chief Financial Officer',
   'yearBorn': 1978,
   'fiscalYear': 2023,
   'totalPay': 278000,
   'exercisedValue': 8517957,
   'unexercisedValue': 202075632},
  {'maxAge': 1,
   'name': 'Mr. Xiaotong  Zhu',
   'age': 43,
   'title': 'Senior Vice President of Automotive',
   'yearBorn': 1980,
   'fiscalYear': 2023,
   'totalPay': 926877,
   'exercisedValue': 0,
   'unexercisedValue': 344144320},
  {'maxAge': 1,
   'name': 'Travis  Axelrod',
   'title': 'Head of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brian  Scelfo',
   'title': 'Senior Director of Corporate Development',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Franz  von Holzhausen',
   'title': 'Chief Designer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. John  Walker',
   'age': 60,
   'title': 'Vice President of Sales - North America',
   'yearBorn': 1963,
   'fiscalYear': 2023,
   'totalPay': 121550,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Peter  Bannon',
   'title': 'Chip Architect',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Turner  Caldwell',
   'title': 'Engineering Manager',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Rodney D. Westmoreland Jr.',
   'title': 'Director of Construction Management',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 9,
 'compensationRisk': 10,
 'shareHolderRightsRisk': 9,
 'overallRisk': 10,
 'governanceEpochDate': 1727740800,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 260.48,
 'open': 255.99,
 'dayLow': 255.32,
 'dayHigh': 269.44,
 'regularMarketPreviousClose': 260.48,
 'regularMarketOpen': 255.99,
 'regularMarketDayLow': 255.32,
 'regularMarketDayHigh': 269.44,
 'beta': 2.297,
 'trailingPE': 73.1863,
 'forwardPE': 84.53481,
 'volume': 141673363,
 'regularMarketVolume': 141673363,
 'averageVolume': 79079650,
 'averageVolume10days': 81711100,
 'averageDailyVolume10Day': 81711100,
 'marketCap': 857503367168,
 'fiftyTwoWeekLow': 138.8,
 'fiftyTwoWeekHigh': 271.0,
 'priceToSalesTrailing12Months': 8.8265915,
 'fiftyDayAverage': 229.4684,
 'twoHundredDayAverage': 201.39536,
 'currency': 'USD',
 'enterpriseValue': 816070328320,
 'profitMargins': 0.13075,
 'floatShares': 2791050572,
 'sharesOutstanding': 3210060032,
 'sharesShort': 74332630,
 'sharesShortPriorMonth': 78698016,
 'sharesShortPreviousMonthDate': 1724976000,
 'dateShortInterest': 1727654400,
 'sharesPercentSharesOut': 0.0233,
 'heldPercentInsiders': 0.12976,
 'heldPercentInstitutions': 0.47035998,
 'shortRatio': 0.93,
 'shortPercentOfFloat': 0.026700001,
 'impliedSharesOutstanding': 3194639872,
 'bookValue': 21.806,
 'priceToBook': 12.2502985,
 'lastFiscalYearEnd': 1703980800,
 'nextFiscalYearEnd': 1735603200,
 'mostRecentQuarter': 1727654400,
 'earningsQuarterlyGrowth': 0.169,
 'netIncomeToCommon': 12743000064,
 'trailingEps': 3.65,
 'forwardEps': 3.16,
 'pegRatio': 51.68,
 'lastSplitFactor': '3:1',
 'lastSplitDate': 1661385600,
 'enterpriseToRevenue': 8.4,
 'enterpriseToEbitda': 61.618,
 '52WeekChange': 0.25653636,
 'SandP52WeekChange': 0.41106093,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'TSLA',
 'underlyingSymbol': 'TSLA',
 'shortName': 'Tesla, Inc.',
 'longName': 'Tesla, Inc.',
 'firstTradeDateEpochUtc': 1277818200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': 'ec367bc4-f92c-397c-ac81-bf7b43cffaf7',
 'messageBoardId': 'finmb_27444752',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 267.13,
 'targetHighPrice': 310.0,
 'targetLowPrice': 24.86,
 'targetMeanPrice': 213.65,
 'targetMedianPrice': 221.0,
 'recommendationMean': 2.8,
 'recommendationKey': 'hold',
 'numberOfAnalystOpinions': 45,
 'totalCash': 33648001024,
 'totalCashPerShare': 10.482,
 'ebitda': 13244000256,
 'totalDebt': 12782999552,
 'quickRatio': 1.214,
 'currentRatio': 1.844,
 'totalRevenue': 97150001152,
 'debtToEquity': 18.078,
 'revenuePerShare': 30.457,
 'returnOnAssets': 0.04759,
 'returnOnEquity': 0.20389,
 'freeCashflow': 676625024,
 'operatingCashflow': 14478999552,
 'earningsGrowth': 0.17,
 'revenueGrowth': 0.078,
 'grossMargins': 0.18229,
 'ebitdaMargins': 0.13633001,
 'operatingMargins': 0.107889995,
 'financialCurrency': 'USD',
 'trailingPegRatio': 8.1631}

In [16]:
msft.get_shares_full(start='2022-01-01', end=None) # a series of full shares on each day

2022-02-04 00:00:00-05:00    1020630016
2022-02-05 00:00:00-05:00    1004259968
2022-02-08 00:00:00-05:00    1033510016
2022-02-11 00:00:00-05:00    1033510016
2022-03-04 00:00:00-05:00    1083500032
                                ...
2024-10-16 00:00:00-04:00    3194639872
2024-10-18 00:00:00-04:00    3194639872
2024-10-19 00:00:00-04:00    3194639872
2024-10-24 00:00:00-04:00    3194639872
2024-10-25 00:00:00-04:00    3210060032
Length: 249, dtype: int64

In [15]:
msft.calendar

{'Dividend Date': datetime.date(2024, 12, 11),
 'Ex-Dividend Date': datetime.date(2024, 11, 20),
 'Earnings Date': [datetime.date(2024, 10, 30)],
 'Earnings High': 3.17,
 'Earnings Low': 2.96,
 'Earnings Average': 3.09,
 'Revenue High': 65196500000,
 'Revenue Low': 64221700000,
 'Revenue Average': 64479400000}

In [17]:
msft.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value
0,2023-06-30,Vanguard Group Inc,0.0701,222486933,58240404451
1,2023-06-30,Blackrock Inc.,0.0586,185889398,48660267714
2,2023-06-30,State Street Corporation,0.0328,104115390,27254285640
3,2023-06-30,"Geode Capital Management, LLC",0.0163,51656526,13522128811
4,2023-06-30,Capital World Investors,0.0133,42272512,11065675466
5,2023-06-30,"FMR, LLC",0.0091,28771552,7531529167
6,2022-12-31,Norges Bank Investment Management,0.0088,28085245,3459540479
7,2023-06-30,Morgan Stanley,0.0088,27983350,7325201529
8,2023-06-30,Price (T.Rowe) Associates Inc,0.0088,27984161,7325413824
9,2023-06-30,JP Morgan Chase & Company,0.0084,26739940,6999714093

In [18]:
msft.mutualfund_holders

,Date Reported,Holder,pctHeld,Shares,Value
0,2023-06-30,Vanguard Total Stock Market Index Fund,0.0265,84022098,21994464593
1,2023-06-30,Vanguard 500 Index Fund,0.0202,64144346,16791065452
2,2023-05-31,Fidelity 500 Index Fund,0.0095,30095622,6137400194
3,2023-08-31,SPDR S&P 500 ETF Trust,0.0094,29683481,7660712776
4,2023-08-31,"Invesco ETF Tr-Invesco QQQ Tr, Series 1 ETF",0.0079,25046231,6463931296
5,2023-08-31,iShares Core S&P 500 ETF,0.0079,25198117,6503130035
6,2023-06-30,Growth Fund Of America Inc,0.0074,23446964,6137711766
7,2023-06-30,Vanguard Growth Index Fund,0.0072,22921725,6000219953
8,2023-06-30,Vanguard Institutional Index Fund-Institutiona...,0.0058,18390595,4814106053
9,2023-08-31,Select Sector SPDR Fund-Consumer Discretionary,0.0041,12989732,3352390034

In [19]:
msft.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m          4    4     8     6           1
1    -1m          8   14    20     8           4
2    -2m          7   12    20     8           4
3    -3m          7   12    21     6           4

In [20]:
msft.analyst_price_targets

{'current': 267.36,
 'low': 24.86,
 'high': 310.0,
 'mean': 213.65,
 'median': 221.0}

In [24]:
msft.earnings_estimate

     numberOfAnalysts    avg    low   high  yearAgoEps  growth
0q                 30   3.09   2.96   3.17        2.73   0.132
+1q                30   3.22   3.07   3.37        2.93   0.099
0y                 42  13.07  12.74  13.64       11.80   0.108
+1y                41  15.22  14.23  16.26       13.07   0.164

In [24]:
data = yf.download('goog', period='1mo')
data

[*********************100%***********************]  1 of 1 completed

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,GOOG,GOOG,GOOG,GOOG,GOOG,GOOG
Date,,,,,,
2024-09-25 00:00:00+00:00,162.990005,162.990005,164.216995,162.774994,162.970001,13607900
2024-09-26 00:00:00+00:00,163.830002,163.830002,165.500000,163.500000,165.029999,18234500
2024-09-27 00:00:00+00:00,165.289993,165.289993,166.970001,163.830002,163.910004,13604300
2024-09-30 00:00:00+00:00,167.190002,167.190002,167.360001,164.639999,164.779999,14070100
2024-10-01 00:00:00+00:00,168.419998,168.419998,170.440002,165.899994,168.860001,18629500
2024-10-02 00:00:00+00:00,167.309998,167.309998,168.880005,166.250000,167.759995,12745000
2024-10-03 00:00:00+00:00,167.210007,167.210007,167.910004,165.369995,165.820007,11004300
2024-10-04 00:00:00+00:00,168.559998,168.559998,169.550003,166.960007,169.339996,11422100
2024-10-07 00:00:00+00:00,164.389999,164.389999,169.899994,164.130005,169.139999,14034700
2024-10-08 00:00:00+00:00,165.699997,165.699997,166.100006,164.309998,165.429993,11723900
2024-10-09 00:00:00+00:00,163.059998,163.059998,166.259995,161.119995,164.854996,19666400
2024-10-10 00:00:00+00:00,163.179993,163.179993,164.311005,161.639999,162.110001,12900500
2024-10-11 00:00:00+00:00,164.520004,164.520004,165.270004,162.500000,163.330002,10946000
2024-10-14 00:00:00+00:00,166.350006,166.350006,167.619995,164.779999,164.910004,9981800
2024-10-15 00:00:00+00:00,166.899994,166.899994,169.089996,166.050003,167.139999,14829300
2024-10-16 00:00:00+00:00,166.740005,166.740005,167.279999,165.216003,166.029999,9968500
2024-10-17 00:00:00+00:00,164.509995,164.509995,167.929993,164.369995,167.380005,15113400
2024-10-18 00:00:00+00:00,165.050003,165.050003,166.369995,164.750000,164.869995,13091300
2024-10-21 00:00:00+00:00,165.800003,165.800003,166.220001,164.304993,164.580002,11384000
2024-10-22 00:00:00+00:00,166.820007,166.820007,167.470001,164.669998,164.699997,11958600
2024-10-23 00:00:00+00:00,164.479996,164.479996,167.600006,163.632996,166.429993,12754300
2024-10-24 00:00:00+00:00,164.529999,164.529999,165.050003,162.770004,164.589996,12764400
2024-10-25 00:00:00+00:00,166.818497,166.818497,167.399994,165.229996,165.365005,8358568

In [34]:
data.dtypes

Price      Ticker
Adj Close  AAPL      float64
           GOOG      float64
Close      AAPL      float64
           GOOG      float64
High       AAPL      float64
           GOOG      float64
Low        AAPL      float64
           GOOG      float64
Open       AAPL      float64
           GOOG      float64
Volume     AAPL        int64
           GOOG        int64
dtype: object

In [25]:
type(data)

pandas.core.frame.DataFrame

In [26]:
tech = yf.Sector('technology')
tech.top_companies

                                                name rating  market weight
symbol
AAPL                                      Apple Inc.    Buy       0.187372
NVDA                              NVIDIA Corporation    Buy       0.185124
MSFT                           Microsoft Corporation    Buy       0.169331
AVGO                                   Broadcom Inc.    Buy       0.043168
ORCL                              Oracle Corporation    Buy       0.025594
CRM                                 Salesforce, Inc.    Buy       0.014730
AMD                     Advanced Micro Devices, Inc.    Buy       0.013443
ACN                                    Accenture plc    Buy       0.011976
CSCO                             Cisco Systems, Inc.    Buy       0.011888
ADBE                                      Adobe Inc.    Buy       0.011306
IBM      International Business Machines Corporation   Hold       0.010534
NOW                                 ServiceNow, Inc.    Buy       0.010419
QCOM                           QUALCOMM Incorporated    Buy       0.010113
TXN                   Texas Instruments Incorporated   Hold       0.010057
INTU                                     Intuit Inc.    Buy       0.009067
UBER                         Uber Technologies, Inc.    Buy       0.008797
AMAT                         Applied Materials, Inc.    Buy       0.008206
ANET                           Arista Networks, Inc.    Buy       0.006592
MU                           Micron Technology, Inc.    Buy       0.006381
PANW                        Palo Alto Networks, Inc.    Buy       0.006342
ADP                  Automatic Data Processing, Inc.   Hold       0.006258
ADI                             Analog Devices, Inc.    Buy       0.006099
FI                                      Fiserv, Inc.    Buy       0.006041
LRCX                        Lam Research Corporation    Buy       0.005395
PLTR                      Palantir Technologies Inc.   Hold       0.005365
INTC                               Intel Corporation   Hold       0.005195
KLAC                                 KLA Corporation    Buy       0.004813
DELL                          Dell Technologies Inc.    Buy       0.004585
APH                             Amphenol Corporation    Buy       0.004434
MSI                         Motorola Solutions, Inc.    Buy       0.004107
SNPS                                  Synopsys, Inc.    Buy       0.004102
CRWD                      CrowdStrike Holdings, Inc.    Buy       0.003892
MRVL                        Marvell Technology, Inc.    Buy       0.003776
CDNS                    Cadence Design Systems, Inc.    Buy       0.003752
WDAY                                   Workday, Inc.    Buy       0.003357
NXPI                         NXP Semiconductors N.V.    Buy       0.003299
ADSK                                  Autodesk, Inc.    Buy       0.003282
FTNT                                  Fortinet, Inc.   Hold       0.003268
TTD                             The Trade Desk, Inc.    Buy       0.003124
ROP                         Roper Technologies, Inc.    Buy       0.003088
APP                             AppLovin Corporation    Buy       0.002870
PAYX                                   Paychex, Inc.   Hold       0.002689
TEAM                           Atlassian Corporation    Buy       0.002622
FIS     Fidelity National Information Services, Inc.    Buy       0.002607
FICO                          Fair Isaac Corporation    Buy       0.002605
MSTR                      MicroStrategy Incorporated    Buy       0.002517
TEL                              TE Connectivity plc    Buy       0.002409
MPWR                  Monolithic Power Systems, Inc.    Buy       0.002353
SQ                                       Block, Inc.    Buy       0.002337
DDOG                                   Datadog, Inc.    Buy       0.002265

In [35]:
msft = yf.Ticker('MSFT')
tech = yf.Sector(msft.info.get('sectorKey'))
software = yf.Industry(msft.info.get('industryKey'))
tech.top_companies

                                                name rating  market weight
symbol
AAPL                                      Apple Inc.    Buy       0.187571
NVDA                              NVIDIA Corporation    Buy       0.184803
MSFT                           Microsoft Corporation    Buy       0.169441
AVGO                                   Broadcom Inc.    Buy       0.042985
ORCL                              Oracle Corporation    Buy       0.025601
CRM                                 Salesforce, Inc.    Buy       0.014784
AMD                     Advanced Micro Devices, Inc.    Buy       0.013463
ACN                                    Accenture plc    Buy       0.012003
CSCO                             Cisco Systems, Inc.    Buy       0.011897
ADBE                                      Adobe Inc.    Buy       0.011337
IBM      International Business Machines Corporation   Hold       0.010528
NOW                                 ServiceNow, Inc.    Buy       0.010422
QCOM                           QUALCOMM Incorporated    Buy       0.010099
TXN                   Texas Instruments Incorporated   Hold       0.010050
INTU                                     Intuit Inc.    Buy       0.009092
UBER                         Uber Technologies, Inc.    Buy       0.008843
AMAT                         Applied Materials, Inc.    Buy       0.008187
ANET                           Arista Networks, Inc.    Buy       0.006592
MU                           Micron Technology, Inc.    Buy       0.006370
PANW                        Palo Alto Networks, Inc.    Buy       0.006352
ADP                  Automatic Data Processing, Inc.   Hold       0.006253
ADI                             Analog Devices, Inc.    Buy       0.006084
FI                                      Fiserv, Inc.    Buy       0.006044
LRCX                        Lam Research Corporation    Buy       0.005361
PLTR                      Palantir Technologies Inc.   Hold       0.005351
INTC                               Intel Corporation   Hold       0.005163
KLAC                                 KLA Corporation    Buy       0.004801
DELL                          Dell Technologies Inc.    Buy       0.004580
APH                             Amphenol Corporation    Buy       0.004451
MSI                         Motorola Solutions, Inc.    Buy       0.004107
SNPS                                  Synopsys, Inc.    Buy       0.004102
CRWD                      CrowdStrike Holdings, Inc.    Buy       0.003923
MRVL                        Marvell Technology, Inc.    Buy       0.003764
CDNS                    Cadence Design Systems, Inc.    Buy       0.003751
WDAY                                   Workday, Inc.    Buy       0.003354
NXPI                         NXP Semiconductors N.V.    Buy       0.003298
ADSK                                  Autodesk, Inc.    Buy       0.003282
FTNT                                  Fortinet, Inc.   Hold       0.003272
TTD                             The Trade Desk, Inc.    Buy       0.003137
ROP                         Roper Technologies, Inc.    Buy       0.003093
APP                             AppLovin Corporation    Buy       0.002876
PAYX                                   Paychex, Inc.   Hold       0.002689
TEAM                           Atlassian Corporation    Buy       0.002618
FICO                          Fair Isaac Corporation    Buy       0.002611
FIS     Fidelity National Information Services, Inc.    Buy       0.002606
MSTR                      MicroStrategy Incorporated    Buy       0.002528
TEL                              TE Connectivity plc    Buy       0.002413
SQ                                       Block, Inc.    Buy       0.002342
MPWR                  Monolithic Power Systems, Inc.    Buy       0.002339
DDOG                                   Datadog, Inc.    Buy       0.002273

In [28]:
# Define a list of ticker symbols to download
tickerStrings = ['AAPL', 'MSFT']

# Download 2 days of data for each ticker, grouping by 'Ticker' to structure the DataFrame with multi-level columns
df = yf.download(tickerStrings, group_by='Ticker', period='5d')
df.head()

[*********************100%***********************]  2 of 2 completed

Ticker                           MSFT                                      \
Price                            Open        High         Low       Close
Date
2024-10-21 00:00:00+00:00  416.119995  418.959991  413.750000  418.779999
2024-10-22 00:00:00+00:00  418.489990  430.579987  418.040009  427.510010
2024-10-23 00:00:00+00:00  430.859985  431.079987  422.529999  424.600006
2024-10-24 00:00:00+00:00  425.329987  425.980011  422.399994  424.730011
2024-10-25 00:00:00+00:00  426.899994  432.500000  426.600006  428.166992

Ticker                                                 AAPL              \
Price                       Adj Close    Volume        Open        High
Date
2024-10-21 00:00:00+00:00  418.779999  14206100  234.449997  236.850006
2024-10-22 00:00:00+00:00  427.510010  25482200  233.889999  236.220001
2024-10-23 00:00:00+00:00  424.600006  19654400  234.080002  235.139999
2024-10-24 00:00:00+00:00  424.730011  13581600  229.979996  230.820007
2024-10-25 00:00:00+00:00  428.166992  11587074  229.740005  233.199997

Ticker
Price                             Low       Close   Adj Close    Volume
Date
2024-10-21 00:00:00+00:00  234.449997  236.479996  236.479996  36254500
2024-10-22 00:00:00+00:00  232.600006  235.860001  235.860001  38846600
2024-10-23 00:00:00+00:00  227.759995  230.759995  230.759995  52287000
2024-10-24 00:00:00+00:00  228.410004  230.570007  230.570007  31109500
2024-10-25 00:00:00+00:00  229.570007  231.490005  231.490005  23124114

In [29]:
df = df.stack(level=0)
df.head()

Price                              Adj Close       Close        High  \
Date                      Ticker
2024-10-21 00:00:00+00:00 AAPL    236.479996  236.479996  236.850006
                          MSFT    418.779999  418.779999  418.959991
2024-10-22 00:00:00+00:00 AAPL    235.860001  235.860001  236.220001
                          MSFT    427.510010  427.510010  430.579987
2024-10-23 00:00:00+00:00 AAPL    230.759995  230.759995  235.139999

Price                                    Low        Open    Volume
Date                      Ticker
2024-10-21 00:00:00+00:00 AAPL    234.449997  234.449997  36254500
                          MSFT    413.750000  416.119995  14206100
2024-10-22 00:00:00+00:00 AAPL    232.600006  233.889999  38846600
                          MSFT    418.040009  418.489990  25482200
2024-10-23 00:00:00+00:00 AAPL    227.759995  234.080002  52287000

In [30]:
df = df.rename_axis(['Date', 'Ticker'])
df.head()

Price                              Adj Close       Close        High  \
Date                      Ticker
2024-10-21 00:00:00+00:00 AAPL    236.479996  236.479996  236.850006
                          MSFT    418.779999  418.779999  418.959991
2024-10-22 00:00:00+00:00 AAPL    235.860001  235.860001  236.220001
                          MSFT    427.510010  427.510010  430.579987
2024-10-23 00:00:00+00:00 AAPL    230.759995  230.759995  235.139999

Price                                    Low        Open    Volume
Date                      Ticker
2024-10-21 00:00:00+00:00 AAPL    234.449997  234.449997  36254500
                          MSFT    413.750000  416.119995  14206100
2024-10-22 00:00:00+00:00 AAPL    232.600006  233.889999  38846600
                          MSFT    418.040009  418.489990  25482200
2024-10-23 00:00:00+00:00 AAPL    227.759995  234.080002  52287000

In [31]:
df = df.reset_index(level=1)
df.head()

Price,Ticker,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,,
2024-10-21 00:00:00+00:00,AAPL,236.479996,236.479996,236.850006,234.449997,234.449997,36254500
2024-10-21 00:00:00+00:00,MSFT,418.779999,418.779999,418.959991,413.750000,416.119995,14206100
2024-10-22 00:00:00+00:00,AAPL,235.860001,235.860001,236.220001,232.600006,233.889999,38846600
2024-10-22 00:00:00+00:00,MSFT,427.510010,427.510010,430.579987,418.040009,418.489990,25482200
2024-10-23 00:00:00+00:00,AAPL,230.759995,230.759995,235.139999,227.759995,234.080002,52287000

In [38]:
# Define a list of ticker symbols to download
tickerStrings = ['AAPL']

# Download 2 days of data for each ticker, grouping by 'Ticker' to structure the DataFrame with multi-level columns
df = yf.download(tickerStrings, group_by='Ticker', period='1y')
df

[*********************100%***********************]  1 of 1 completed

Ticker                           AAPL                                      \
Price                            Open        High         Low       Close
Date
2023-10-26 00:00:00+00:00  170.369995  171.380005  165.669998  166.889999
2023-10-27 00:00:00+00:00  166.910004  168.960007  166.830002  168.220001
2023-10-30 00:00:00+00:00  169.020004  171.169998  168.869995  170.289993
2023-10-31 00:00:00+00:00  169.350006  170.899994  167.899994  170.770004
2023-11-01 00:00:00+00:00  171.000000  174.229996  170.119995  173.970001
...                               ...         ...         ...         ...
2024-10-21 00:00:00+00:00  234.449997  236.850006  234.449997  236.479996
2024-10-22 00:00:00+00:00  233.889999  236.220001  232.600006  235.860001
2024-10-23 00:00:00+00:00  234.080002  235.139999  227.759995  230.759995
2024-10-24 00:00:00+00:00  229.979996  230.820007  228.410004  230.570007
2024-10-25 00:00:00+00:00  229.740005  233.199997  229.570007  231.410004

Ticker
Price                       Adj Close    Volume
Date
2023-10-26 00:00:00+00:00  166.040344  70625300
2023-10-27 00:00:00+00:00  167.363586  58499100
2023-10-30 00:00:00+00:00  169.423035  51131000
2023-10-31 00:00:00+00:00  169.900604  44846000
2023-11-01 00:00:00+00:00  173.084305  56934900
...                               ...       ...
2024-10-21 00:00:00+00:00  236.479996  36254500
2024-10-22 00:00:00+00:00  235.860001  38846600
2024-10-23 00:00:00+00:00  230.759995  52287000
2024-10-24 00:00:00+00:00  230.570007  31109500
2024-10-25 00:00:00+00:00  231.410004  37918358

[252 rows x 6 columns]